import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	metafile: true,
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
	},
	plugins: [
		{
			name: 'bundle-analysis',
			setup(build) {
				build.onEnd((result) => {
					if (result.metafile) {
						console.log('\nBundle analysis:');
						const outputs = result.metafile.outputs;
						const mainBundle = outputs['main.js'];
						if (mainBundle) {
							const sizeKB = (mainBundle.bytes / 1024).toFixed(2);
							console.log(`main.js: ${sizeKB} KB`);
							
							// Check if we're under the 300KB target
							if (parseFloat(sizeKB) > 300) {
								console.warn('⚠️  Bundle size exceeds 300KB target!');
							} else {
								console.log('✅ Bundle size within target');
							}
						}
					}
				});
			},
		},
		{
			name: 'stockfish-wasm-loader',
			setup(build) {
				build.onResolve({ filter: /stockfish\.wasm\.js$/ }, args => {
					return { path: args.path, namespace: 'stockfish-wasm' };
				});
				build.onLoad({ filter: /.*/, namespace: 'stockfish-wasm' }, async () => {
					const fs = await import('fs');
					const path = await import('path');
					const stockfishPath = path.resolve('node_modules/stockfish.js/stockfish.wasm.js');
					const content = fs.readFileSync(stockfishPath, 'utf8');
					const augmentedSource = `${content}\nreturn Module;`;
					return {
						contents: `const STOCKFISH_SOURCE = ${JSON.stringify(augmentedSource)};

const stockfishFactory = new Function('Module', STOCKFISH_SOURCE);

export function initializeStockfishModule(Module) {
	const previousPostMessage = globalThis.postMessage;
	const previousOnmessage = globalThis.onmessage;
	const previousClose = globalThis.close;
	const stubPostMessage = (message) => {
		if (Module && typeof Module.__postMessage === 'function') {
			Module.__postMessage(message);
		}
	};
	globalThis.postMessage = stubPostMessage;
	globalThis.onmessage = function () {};
	globalThis.close = function () {};
	try {
		return stockfishFactory(Module);
	} finally {
		globalThis.postMessage = previousPostMessage;
		globalThis.onmessage = previousOnmessage;
		globalThis.close = previousClose;
	}
}

export default initializeStockfishModule;
`,
						loader: 'js',
					};
				});
				build.onResolve({ filter: /stockfish\.wasm$/ }, args => {
					return { path: args.path, namespace: 'stockfish-wasm-binary' };
				});
				build.onLoad({ filter: /.*/, namespace: 'stockfish-wasm-binary' }, async (args) => {
					const fs = await import('fs');
					const path = await import('path');
					const wasmPath = path.resolve('node_modules/stockfish.js/stockfish.wasm');
					const wasmBinary = fs.readFileSync(wasmPath);
					const base64 = wasmBinary.toString('base64');
					return {
						contents: `export default '${base64}';`,
						loader: 'js',
					};
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
